//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaCNPJ.WSSepd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sped.fazenda.gov.br/", ConfigurationName="WSSepd.WsConsultaSoap")]
    public interface WsConsultaSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://sped.fazenda.gov.br/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesCadastrais", ReplyAction="*")]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponse ConsultarInformacoesCadastrais(ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesCadastrais", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponse> ConsultarInformacoesCadastraisAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://sped.fazenda.gov.br/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesIntermediario", ReplyAction="*")]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponse ConsultarInformacoesIntermediario(ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesIntermediario", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponse> ConsultarInformacoesIntermediarioAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://sped.fazenda.gov.br/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesPatrocinado", ReplyAction="*")]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponse ConsultarInformacoesPatrocinado(ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesPatrocinado", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponse> ConsultarInformacoesPatrocinadoAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://sped.fazenda.gov.br/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarListaEFinanceira", ReplyAction="*")]
        ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponse ConsultarListaEFinanceira(ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarListaEFinanceira", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponse> ConsultarListaEFinanceiraAsync(ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cnpj no namespace http://sped.fazenda.gov.br/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesMovimento", ReplyAction="*")]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponse ConsultarInformacoesMovimento(ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesMovimento", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponse> ConsultarInformacoesMovimentoAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento situacaoInformacao no namespace http://sped.fazenda.gov.br/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesRerct", ReplyAction="*")]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponse ConsultarInformacoesRerct(ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultarInformacoesRerct", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponse> ConsultarInformacoesRerctAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesCadastraisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesCadastrais", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequestBody Body;
        
        public ConsultarInformacoesCadastraisRequest() {
        }
        
        public ConsultarInformacoesCadastraisRequest(ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesCadastraisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        public ConsultarInformacoesCadastraisRequestBody() {
        }
        
        public ConsultarInformacoesCadastraisRequestBody(string cnpj) {
            this.cnpj = cnpj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesCadastraisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesCadastraisResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponseBody Body;
        
        public ConsultarInformacoesCadastraisResponse() {
        }
        
        public ConsultarInformacoesCadastraisResponse(ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesCadastraisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ConsultarInformacoesCadastraisResult;
        
        public ConsultarInformacoesCadastraisResponseBody() {
        }
        
        public ConsultarInformacoesCadastraisResponseBody(System.Xml.Linq.XElement ConsultarInformacoesCadastraisResult) {
            this.ConsultarInformacoesCadastraisResult = ConsultarInformacoesCadastraisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesIntermediarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesIntermediario", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequestBody Body;
        
        public ConsultarInformacoesIntermediarioRequest() {
        }
        
        public ConsultarInformacoesIntermediarioRequest(ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesIntermediarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GINN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoNI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NumeroIdentificacao;
        
        public ConsultarInformacoesIntermediarioRequestBody() {
        }
        
        public ConsultarInformacoesIntermediarioRequestBody(string cnpj, string GINN, string TipoNI, string NumeroIdentificacao) {
            this.cnpj = cnpj;
            this.GINN = GINN;
            this.TipoNI = TipoNI;
            this.NumeroIdentificacao = NumeroIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesIntermediarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesIntermediarioResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponseBody Body;
        
        public ConsultarInformacoesIntermediarioResponse() {
        }
        
        public ConsultarInformacoesIntermediarioResponse(ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesIntermediarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ConsultarInformacoesIntermediarioResult;
        
        public ConsultarInformacoesIntermediarioResponseBody() {
        }
        
        public ConsultarInformacoesIntermediarioResponseBody(System.Xml.Linq.XElement ConsultarInformacoesIntermediarioResult) {
            this.ConsultarInformacoesIntermediarioResult = ConsultarInformacoesIntermediarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesPatrocinadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesPatrocinado", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequestBody Body;
        
        public ConsultarInformacoesPatrocinadoRequest() {
        }
        
        public ConsultarInformacoesPatrocinadoRequest(ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesPatrocinadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GINN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumeroIdentificacao;
        
        public ConsultarInformacoesPatrocinadoRequestBody() {
        }
        
        public ConsultarInformacoesPatrocinadoRequestBody(string cnpj, string GINN, string NumeroIdentificacao) {
            this.cnpj = cnpj;
            this.GINN = GINN;
            this.NumeroIdentificacao = NumeroIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesPatrocinadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesPatrocinadoResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponseBody Body;
        
        public ConsultarInformacoesPatrocinadoResponse() {
        }
        
        public ConsultarInformacoesPatrocinadoResponse(ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesPatrocinadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ConsultarInformacoesPatrocinadoResult;
        
        public ConsultarInformacoesPatrocinadoResponseBody() {
        }
        
        public ConsultarInformacoesPatrocinadoResponseBody(System.Xml.Linq.XElement ConsultarInformacoesPatrocinadoResult) {
            this.ConsultarInformacoesPatrocinadoResult = ConsultarInformacoesPatrocinadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarListaEFinanceiraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarListaEFinanceira", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequestBody Body;
        
        public ConsultarListaEFinanceiraRequest() {
        }
        
        public ConsultarListaEFinanceiraRequest(ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarListaEFinanceiraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int situacaoEFinanceira;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> dataInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> dataFim;
        
        public ConsultarListaEFinanceiraRequestBody() {
        }
        
        public ConsultarListaEFinanceiraRequestBody(string cnpj, int situacaoEFinanceira, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFim) {
            this.cnpj = cnpj;
            this.situacaoEFinanceira = situacaoEFinanceira;
            this.dataInicio = dataInicio;
            this.dataFim = dataFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarListaEFinanceiraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarListaEFinanceiraResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponseBody Body;
        
        public ConsultarListaEFinanceiraResponse() {
        }
        
        public ConsultarListaEFinanceiraResponse(ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarListaEFinanceiraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ConsultarListaEFinanceiraResult;
        
        public ConsultarListaEFinanceiraResponseBody() {
        }
        
        public ConsultarListaEFinanceiraResponseBody(System.Xml.Linq.XElement ConsultarListaEFinanceiraResult) {
            this.ConsultarListaEFinanceiraResult = ConsultarListaEFinanceiraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesMovimentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesMovimento", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequestBody Body;
        
        public ConsultarInformacoesMovimentoRequest() {
        }
        
        public ConsultarInformacoesMovimentoRequest(ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesMovimentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnpj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string situacaoInformacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string anoMesInicioVigencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string anoMesTerminoVigencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipoMovimento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tipoIdentificacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string identificacao;
        
        public ConsultarInformacoesMovimentoRequestBody() {
        }
        
        public ConsultarInformacoesMovimentoRequestBody(string cnpj, string situacaoInformacao, string anoMesInicioVigencia, string anoMesTerminoVigencia, string tipoMovimento, string tipoIdentificacao, string identificacao) {
            this.cnpj = cnpj;
            this.situacaoInformacao = situacaoInformacao;
            this.anoMesInicioVigencia = anoMesInicioVigencia;
            this.anoMesTerminoVigencia = anoMesTerminoVigencia;
            this.tipoMovimento = tipoMovimento;
            this.tipoIdentificacao = tipoIdentificacao;
            this.identificacao = identificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesMovimentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesMovimentoResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponseBody Body;
        
        public ConsultarInformacoesMovimentoResponse() {
        }
        
        public ConsultarInformacoesMovimentoResponse(ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesMovimentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ConsultarInformacoesMovimentoResult;
        
        public ConsultarInformacoesMovimentoResponseBody() {
        }
        
        public ConsultarInformacoesMovimentoResponseBody(System.Xml.Linq.XElement ConsultarInformacoesMovimentoResult) {
            this.ConsultarInformacoesMovimentoResult = ConsultarInformacoesMovimentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesRerctRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesRerct", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequestBody Body;
        
        public ConsultarInformacoesRerctRequest() {
        }
        
        public ConsultarInformacoesRerctRequest(ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesRerctRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEventoRerct;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string situacaoInformacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numeroRecibo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cnpjDeclarante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipoInscricaoDeclarado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string inscricaoDeclarado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tipoInscricaoTitular;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string inscricaoTitular;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cpfBeneficiarioFinal;
        
        public ConsultarInformacoesRerctRequestBody() {
        }
        
        public ConsultarInformacoesRerctRequestBody(int idEventoRerct, string situacaoInformacao, string numeroRecibo, string cnpjDeclarante, string tipoInscricaoDeclarado, string inscricaoDeclarado, string tipoInscricaoTitular, string inscricaoTitular, string cpfBeneficiarioFinal) {
            this.idEventoRerct = idEventoRerct;
            this.situacaoInformacao = situacaoInformacao;
            this.numeroRecibo = numeroRecibo;
            this.cnpjDeclarante = cnpjDeclarante;
            this.tipoInscricaoDeclarado = tipoInscricaoDeclarado;
            this.inscricaoDeclarado = inscricaoDeclarado;
            this.tipoInscricaoTitular = tipoInscricaoTitular;
            this.inscricaoTitular = inscricaoTitular;
            this.cpfBeneficiarioFinal = cpfBeneficiarioFinal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarInformacoesRerctResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarInformacoesRerctResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponseBody Body;
        
        public ConsultarInformacoesRerctResponse() {
        }
        
        public ConsultarInformacoesRerctResponse(ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultarInformacoesRerctResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ConsultarInformacoesRerctResult;
        
        public ConsultarInformacoesRerctResponseBody() {
        }
        
        public ConsultarInformacoesRerctResponseBody(System.Xml.Linq.XElement ConsultarInformacoesRerctResult) {
            this.ConsultarInformacoesRerctResult = ConsultarInformacoesRerctResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsConsultaSoapChannel : ConsultaCNPJ.WSSepd.WsConsultaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsConsultaSoapClient : System.ServiceModel.ClientBase<ConsultaCNPJ.WSSepd.WsConsultaSoap>, ConsultaCNPJ.WSSepd.WsConsultaSoap {
        
        public WsConsultaSoapClient() {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponse ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesCadastrais(ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest request) {
            return base.Channel.ConsultarInformacoesCadastrais(request);
        }
        
        public System.Xml.Linq.XElement ConsultarInformacoesCadastrais(string cnpj) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequestBody();
            inValue.Body.cnpj = cnpj;
            ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponse retVal = ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesCadastrais(inValue);
            return retVal.Body.ConsultarInformacoesCadastraisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponse> ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesCadastraisAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest request) {
            return base.Channel.ConsultarInformacoesCadastraisAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisResponse> ConsultarInformacoesCadastraisAsync(string cnpj) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesCadastraisRequestBody();
            inValue.Body.cnpj = cnpj;
            return ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesCadastraisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponse ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesIntermediario(ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest request) {
            return base.Channel.ConsultarInformacoesIntermediario(request);
        }
        
        public System.Xml.Linq.XElement ConsultarInformacoesIntermediario(string cnpj, string GINN, string TipoNI, string NumeroIdentificacao) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.GINN = GINN;
            inValue.Body.TipoNI = TipoNI;
            inValue.Body.NumeroIdentificacao = NumeroIdentificacao;
            ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponse retVal = ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesIntermediario(inValue);
            return retVal.Body.ConsultarInformacoesIntermediarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponse> ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesIntermediarioAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest request) {
            return base.Channel.ConsultarInformacoesIntermediarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioResponse> ConsultarInformacoesIntermediarioAsync(string cnpj, string GINN, string TipoNI, string NumeroIdentificacao) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesIntermediarioRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.GINN = GINN;
            inValue.Body.TipoNI = TipoNI;
            inValue.Body.NumeroIdentificacao = NumeroIdentificacao;
            return ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesIntermediarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponse ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesPatrocinado(ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest request) {
            return base.Channel.ConsultarInformacoesPatrocinado(request);
        }
        
        public System.Xml.Linq.XElement ConsultarInformacoesPatrocinado(string cnpj, string GINN, string NumeroIdentificacao) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.GINN = GINN;
            inValue.Body.NumeroIdentificacao = NumeroIdentificacao;
            ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponse retVal = ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesPatrocinado(inValue);
            return retVal.Body.ConsultarInformacoesPatrocinadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponse> ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesPatrocinadoAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest request) {
            return base.Channel.ConsultarInformacoesPatrocinadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoResponse> ConsultarInformacoesPatrocinadoAsync(string cnpj, string GINN, string NumeroIdentificacao) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesPatrocinadoRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.GINN = GINN;
            inValue.Body.NumeroIdentificacao = NumeroIdentificacao;
            return ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesPatrocinadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponse ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarListaEFinanceira(ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest request) {
            return base.Channel.ConsultarListaEFinanceira(request);
        }
        
        public System.Xml.Linq.XElement ConsultarListaEFinanceira(string cnpj, int situacaoEFinanceira, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFim) {
            ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.situacaoEFinanceira = situacaoEFinanceira;
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponse retVal = ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarListaEFinanceira(inValue);
            return retVal.Body.ConsultarListaEFinanceiraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponse> ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarListaEFinanceiraAsync(ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest request) {
            return base.Channel.ConsultarListaEFinanceiraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraResponse> ConsultarListaEFinanceiraAsync(string cnpj, int situacaoEFinanceira, System.Nullable<System.DateTime> dataInicio, System.Nullable<System.DateTime> dataFim) {
            ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarListaEFinanceiraRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.situacaoEFinanceira = situacaoEFinanceira;
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            return ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarListaEFinanceiraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponse ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesMovimento(ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest request) {
            return base.Channel.ConsultarInformacoesMovimento(request);
        }
        
        public System.Xml.Linq.XElement ConsultarInformacoesMovimento(string cnpj, string situacaoInformacao, string anoMesInicioVigencia, string anoMesTerminoVigencia, string tipoMovimento, string tipoIdentificacao, string identificacao) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.situacaoInformacao = situacaoInformacao;
            inValue.Body.anoMesInicioVigencia = anoMesInicioVigencia;
            inValue.Body.anoMesTerminoVigencia = anoMesTerminoVigencia;
            inValue.Body.tipoMovimento = tipoMovimento;
            inValue.Body.tipoIdentificacao = tipoIdentificacao;
            inValue.Body.identificacao = identificacao;
            ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponse retVal = ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesMovimento(inValue);
            return retVal.Body.ConsultarInformacoesMovimentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponse> ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesMovimentoAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest request) {
            return base.Channel.ConsultarInformacoesMovimentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoResponse> ConsultarInformacoesMovimentoAsync(string cnpj, string situacaoInformacao, string anoMesInicioVigencia, string anoMesTerminoVigencia, string tipoMovimento, string tipoIdentificacao, string identificacao) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesMovimentoRequestBody();
            inValue.Body.cnpj = cnpj;
            inValue.Body.situacaoInformacao = situacaoInformacao;
            inValue.Body.anoMesInicioVigencia = anoMesInicioVigencia;
            inValue.Body.anoMesTerminoVigencia = anoMesTerminoVigencia;
            inValue.Body.tipoMovimento = tipoMovimento;
            inValue.Body.tipoIdentificacao = tipoIdentificacao;
            inValue.Body.identificacao = identificacao;
            return ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesMovimentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponse ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesRerct(ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest request) {
            return base.Channel.ConsultarInformacoesRerct(request);
        }
        
        public System.Xml.Linq.XElement ConsultarInformacoesRerct(int idEventoRerct, string situacaoInformacao, string numeroRecibo, string cnpjDeclarante, string tipoInscricaoDeclarado, string inscricaoDeclarado, string tipoInscricaoTitular, string inscricaoTitular, string cpfBeneficiarioFinal) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequestBody();
            inValue.Body.idEventoRerct = idEventoRerct;
            inValue.Body.situacaoInformacao = situacaoInformacao;
            inValue.Body.numeroRecibo = numeroRecibo;
            inValue.Body.cnpjDeclarante = cnpjDeclarante;
            inValue.Body.tipoInscricaoDeclarado = tipoInscricaoDeclarado;
            inValue.Body.inscricaoDeclarado = inscricaoDeclarado;
            inValue.Body.tipoInscricaoTitular = tipoInscricaoTitular;
            inValue.Body.inscricaoTitular = inscricaoTitular;
            inValue.Body.cpfBeneficiarioFinal = cpfBeneficiarioFinal;
            ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponse retVal = ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesRerct(inValue);
            return retVal.Body.ConsultarInformacoesRerctResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponse> ConsultaCNPJ.WSSepd.WsConsultaSoap.ConsultarInformacoesRerctAsync(ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest request) {
            return base.Channel.ConsultarInformacoesRerctAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctResponse> ConsultarInformacoesRerctAsync(int idEventoRerct, string situacaoInformacao, string numeroRecibo, string cnpjDeclarante, string tipoInscricaoDeclarado, string inscricaoDeclarado, string tipoInscricaoTitular, string inscricaoTitular, string cpfBeneficiarioFinal) {
            ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest inValue = new ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequest();
            inValue.Body = new ConsultaCNPJ.WSSepd.ConsultarInformacoesRerctRequestBody();
            inValue.Body.idEventoRerct = idEventoRerct;
            inValue.Body.situacaoInformacao = situacaoInformacao;
            inValue.Body.numeroRecibo = numeroRecibo;
            inValue.Body.cnpjDeclarante = cnpjDeclarante;
            inValue.Body.tipoInscricaoDeclarado = tipoInscricaoDeclarado;
            inValue.Body.inscricaoDeclarado = inscricaoDeclarado;
            inValue.Body.tipoInscricaoTitular = tipoInscricaoTitular;
            inValue.Body.inscricaoTitular = inscricaoTitular;
            inValue.Body.cpfBeneficiarioFinal = cpfBeneficiarioFinal;
            return ((ConsultaCNPJ.WSSepd.WsConsultaSoap)(this)).ConsultarInformacoesRerctAsync(inValue);
        }
    }
}
